services:
  server:
    image: microblogpub/microblogpub:latest
    container_name: microblogpub
    restart: always
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
    ports:
      - "36287:8000"
