services:
  server:
    image: microblogpub/microblogpub:latest
    container_name: microblogpub
    restart: always
    volumes:
      - ./data:/app/data
      - ./app/static:/app/app/static
      - ./sockets:/run/sockets
    environment:
      UVICORN_UDS: /run/sockets/uvicorn.sock
